apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xstatemachine.sfnaws.example.com
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: sfn.aws.example.com/v1alpha1
    kind: XStateMachine
  mode: Pipeline
  pipeline:
    - step: go-templating
      functionRef:
        name: crossplane-contrib-function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{- $spec := $.observed.composite.resource.spec }}

            {{- $logGroupArn := (dig "resources" "cloudwatch-log-group" "resource" "status" "atProvider" "arn" "" $.observed ) }}
            {{- $stateMachineArn := (dig "resources" "state-machine" "resource" "status" "atProvider" "arn" "" $.observed ) }}
            
            # if user doesn't specify a role, create one
            {{- $roleArn :="" }}
            {{- if $spec.stateMachineParameters.roleArn }}
            {{- $roleArn = $spec.stateMachineParameters.roleArn }}
            {{- else }}
            {{- $roleArn = (dig "resources" "statemachine-role" "resource" "status" "atProvider" "arn" "" $.observed ) }}
            ---
            apiVersion: iam.aws.upbound.io/v1beta1
            kind: Role
            metadata:
              labels:
              {{ $spec.commonLabels | toYaml | nindent 4 }}
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: statemachine-role
            spec:
              deletionPolicy: {{ default "Delete" $spec.deletionPolicy }}
              providerConfigRef:
                name: {{ default "default" $spec.providerConfigName }}
              forProvider:
                assumeRolePolicy: |
                  {
                    "Version": "2012-10-17",
                    "Statement": [
                      {
                        "Effect": "Allow",
                        "Principal": {
                          "Service": "states.amazonaws.com"
                        },
                        "Action": "sts:AssumeRole"
                      }
                    ]
                  }
                inlinePolicy: 
                - name: "sfn-cloudwatchlogs"
                  policy: |
                    {
                      "Version": "2012-10-17",
                      "Statement": [
                        {
                          "Effect": "Allow",
                          "Action": [
                            "logs:CreateLogDelivery",
                                "logs:GetLogDelivery",
                            "logs:UpdateLogDelivery",
                            "logs:DeleteLogDelivery",
                            "logs:ListLogDeliveries",
                            "logs:PutResourcePolicy",
                            "logs:DescribeResourcePolicies",
                              "logs:DescribeLogGroups"
                          ],
                          "Resource": "*"
                        }{{- if $spec.stateMachineParameters.tracingEnabled -}},
                        {
                          "Effect": "Allow",
                          "Action": [
                              "xray:PutTraceSegments",
                              "xray:PutTelemetryRecords",
                              "xray:GetSamplingRules",
                              "xray:GetSamplingTargets"
                          ],
                          "Resource": [
                              "*"
                          ]
                        }
                        {{- end -}}
                      ]
                    }
            {{ end }}
                tags:
                  {{ $spec.tags | toYaml | nindent 6 }}
            ---
            apiVersion: cloudwatchlogs.aws.upbound.io/v1beta1
            kind: Group
            metadata:
              labels:
                {{ $spec.commonLabels | toYaml | nindent 4 }}
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: cloudwatch-log-group
            spec:
              deletionPolicy: {{ default "Delete" $spec.deletionPolicy }}
              providerConfigRef:
                name: {{ default "default" $spec.providerConfigName }}
              forProvider:
                region: {{ $spec.region }}
                retentionInDays: {{ $spec.cloudWatchLogParameters.retentionInDays | int }}
                tags:
                  {{ $spec.tags | toYaml | nindent 6 }}
            {{ if and $logGroupArn $roleArn }}
            ---
            apiVersion: sfn.aws.upbound.io/v1beta1
            kind: StateMachine
            metadata:
              labels:
                {{ $spec.commonLabels | toYaml | nindent 4 }}
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: state-machine
            spec:
              deletionPolicy: {{ default "Delete" $spec.deletionPolicy }}
              providerConfigRef:
                name: {{ default "default" $spec.providerConfigName }}
              forProvider:
                publish: {{ default false $spec.stateMachineParameters.publish }}
                region: {{ $spec.region }}
                loggingConfiguration:
                - includeExecutionData: {{ default false $spec.cloudWatchLogParameters.includeExecutionData }}
                  level: {{ default "ERROR" $spec.cloudWatchLogParameters.logLevel }}
                  logDestination: "{{ $logGroupArn }}:*"
                definition: {{ $spec.stateMachineParameters.definition | toJson }}
                roleArn: {{ $roleArn }}
                tags:
                  {{ $spec.tags | toYaml | nindent 6 }}
                tracingConfiguration:
                - enabled: {{ default false $spec.stateMachineParameters.tracingEnabled }}
                type: EXPRESS # required for logging
            {{ end }}
            ---
            apiVersion: {{ $.observed.composite.resource.apiVersion }}
            kind: {{ $.observed.composite.resource.kind }}
            status:
            {{ if $logGroupArn }}
              cloudWatchLogGroupArn: {{ $logGroupArn }}
            {{ end }}
            {{ if $roleArn }}
              iamRoleArn: {{ $roleArn }}
            {{ end }}
            {{ if $stateMachineArn }}
              stateMachineArn: {{ $stateMachineArn }}
            {{ end }}
    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: crossplane-contrib-function-auto-ready