apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xstatemachines.sfn.aws.example.com
spec:
  claimNames:
    kind: StateMachine
    plural: statemachines
  group: sfn.aws.example.com
  names:
    categories:
      - crossplane
      - composition
      - sfn
    kind: XStateMachine
    plural: xstatemachines
  versions:
    - additionalPrinterColumns:
        - jsonPath: .metadata.annotations.crossplane\.io/external-name
          name: EXTERNAL-NAME
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: AGE
          type: date
      name: v1alpha1
      referenceable: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              description: StateMachineSpec defines the desired state of StateMachine
              properties:
                deletionPolicy:
                  default: Delete
                  description: |-
                    DeletionPolicy specifies what will happen to the underlying external
                    when this managed resource is deleted - either "Delete" or "Orphan" the
                    external resource.
                    This field is planned to be deprecated in favor of the ManagementPolicies
                    field in a future release. Currently, both could be set independently and
                    non-default values would be honored if the feature flag is enabled.
                    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
                  enum:
                    - Orphan
                    - Delete
                  type: string
                providerConfigName:
                  default: default
                  description: Crossplane ProviderConfig to use when provisioning resources
                  type: string
                region:
                  default: us-east-1
                  description: AWS region
                  type: string
                tags:
                  description: AWS tags to add to Resources that support tags
                  additionalProperties:
                    type: string
                  type: object
                  x-kubernetes-map-type: granular
                commonLabels:
                  description: Kubernetes Labels to add to all resources
                  additionalProperties:
                    type: string
                  type: object
                  x-kubernetes-map-type: granular
                cloudWatchLogParameters:
                  type: object
                  properties:
                    retentionInDays:
                      type: integer
                      default: 7
                    includeExecutionData:
                      type: boolean
                      default: false
                    logLevel:
                      default: ERROR
                      type: string
                      enum:
                        - ALL
                        - ERROR
                        - FATAL
                        - "OFF"
                stateMachineParameters:
                  properties:
                    definition:
                      description: The Amazon States Language definition of the state machine.
                      type: string
                    loggingConfiguration:
                      description: Defines what execution history events are logged and where they are logged. The logging_configuration parameter is only valid when type is set to EXPRESS. Defaults to OFF. For more information see Logging Express Workflows and Log Levels in the AWS Step Functions User Guide.
                      items:
                        properties:
                          includeExecutionData:
                            description: Determines whether execution data is included in your log. When set to false, data is excluded.
                            type: boolean
                          level:
                            description: 'Defines which category of execution history events are logged. Valid values: ALL, ERROR, FATAL, OFF'
                            type: string
                          logDestination:
                            description: Amazon Resource Name (ARN) of a CloudWatch log group. Make sure the State Machine has the correct IAM policies for logging. The ARN must end with :*
                            type: string
                        type: object
                      type: array
                    publish:
                      description: 'Set to true to publish a version of the state machine during creation. Default: false.'
                      type: boolean
                    roleArn:
                      description: The Amazon Resource Name (ARN) of the IAM role to use for this state machine. If not Provided an ARN will be created.
                      type: string
                    tracingEnabled:
                      description: When set to true, AWS X-Ray tracing is enabled. Make sure the State Machine has the correct IAM policies for logging. If this composition is creating a Role, X-Ray IAM policies will be added to the role.
                      type: boolean
                      default: false
                  required:
                    - definition
                  type: object
              required:
                - stateMachineParameters
              type: objects
            status:
              description: Status defines the observed state of StateMachine.
              properties:
                resourceStatus:
                  description: Generic Status for all Managed Resources
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                cloudWatchLogGroupArn:
                  description: The ARN of the CloudWatch Log Group
                  type: string
                iamRoleArn:
                  description: The ARN of the IAM Role if created
                  type: string
                stateMachineArn:
                  description: The ARN of the state machine.
                  type: string
                stateMachineStatus:
                  description: Freeform field containing information about the observed status.
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
              type: object
      served: true
