apiVersion: cloudwatchlogs.aws.upbound.io/v1beta1
kind: Group
metadata:
  annotations:
    crossplane.io/composition-resource-name: cloudwatch-log-group
    crossplane.io/external-create-pending: "2024-04-20T00:01:30Z"
    crossplane.io/external-create-succeeded: "2024-04-20T00:01:30Z"
    crossplane.io/external-name: statemachine-wdlfm
  creationTimestamp: "2024-04-20T00:01:29Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: statemachine-
  generation: 3
  labels:
    crossplane.io/claim-name: ""
    crossplane.io/claim-namespace: ""
    crossplane.io/composite: statemachine
  name: statemachine-wdlfm
  ownerReferences:
  - apiVersion: sfn.aws.example.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: XStateMachine
    name: statemachine
    uid: d2602a99-db80-4568-bddb-9dddf891467f
  resourceVersion: "737225"
  uid: 7bc8b3d6-131d-4816-9eb5-58fa5febdc8e
spec:
  deletionPolicy: Delete
  forProvider:
    logGroupClass: STANDARD
    region: us-west-1
    retentionInDays: 0
    tags:
      crossplane-kind: group.cloudwatchlogs.aws.upbound.io
      crossplane-name: statemachine-wdlfm
      crossplane-providerconfig: default
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
status:
  atProvider:
    arn: arn:aws:logs:us-west-1:1234567890:log-group:statemachine-wdlfm
    id: statemachine-wdlfm
    kmsKeyId: ""
    logGroupClass: STANDARD
    retentionInDays: 0
    skipDestroy: false
    tags:
      crossplane-kind: group.cloudwatchlogs.aws.upbound.io
      crossplane-name: statemachine-wdlfm
      crossplane-providerconfig: default
    tagsAll:
      crossplane-kind: group.cloudwatchlogs.aws.upbound.io
      crossplane-name: statemachine-wdlfm
      crossplane-providerconfig: default
  conditions:
  - lastTransitionTime: "2024-04-20T00:01:31Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-04-20T00:01:30Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2024-04-20T00:01:30Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
